### ISSUE TITLE
Async processing

### ISSUE THREAD

**Issue by lmajano** [coldbox-modules/cbox-bugloghq#4]
Make async processing for exceptions and loggings instead of blocking on `cfhttp` calls.

**Comment by coryasilva** [comment]
https://github.com/coldbox-modules/cbox-bugloghq/commit/00b363f921d52c53b9edd1f9f1d4ebcdf0e9cbfe

Just some house cleaning.  I think this has already been completed.  Thank you for the module!

**Comment by lmajano** [comment]
Thanks are you sending a pull?

**Comment by coryasilva** [comment]
No sorry, perhaps I misunderstood this issue?  The changelog said "Added asynchronous capablities to logging for performance" but this issue was still open and it confused me.  I was suggesting that you may have forgot to close it.
